### ISSUE TITLE
rtcninja throws variable not defined error when initializing on Node.js

### ISSUE THREAD

**Issue by bsFirespotter** [ibc/rtcninja.js#7]
> $npm install rtcninja
> $node
> $>rtcninja = require('rtcninja')()

This has to do with the conditional logic. Line 39 in Adapter.js is the culprit.

**Comment by ibc** [comment]
`navigator` is not defined in Node. You may define it in hack-mode before you load rtcninja:

```
global.navigator = {
  userAgent = ''
};
```

**Comment by ibc** [comment]
Anyhow I've just released 0.2.9 (1ffa5f09184e3575ad5313784fe615c8f293da3b) which creates an empty `navigator` Object if it does not exist.
